
name: Sample Workflow

on:
  push:
    branches:
      - main  # This will run the workflow only on pushes to the main branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 22f3001952@ds.study.iitm.ac.in  # This is your step name with your email
        run: echo "This is a test step with my email address."
      - name: 22f3001952@ds.study.iitm.ac.in
        run: echo "Hello, world!"
